# Generated by Django 3.2 on 2022-02-09 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(help_text='Добавьте теги к своему рецепту', through='foodgram.TagRecipe', to='foodgram.Tag', verbose_name='Список id тегов'),
        ),
    ]
