# Generated by Django 3.2 on 2022-02-12 15:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0002_alter_recipe_tags'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favorite',
            name='favorite_unique_favorite_user_recipe',
        ),
        migrations.RemoveConstraint(
            model_name='shoppingcart',
            name='shoppingcart_unique_favorite_user_recipe',
        ),
        migrations.AlterField(
            model_name='ingredientinrecipe',
            name='amount',
            field=models.PositiveSmallIntegerField(help_text='Минимальное количество 1', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество в рецепте'),
        ),
    ]
